<div class="loading"></div>

<div class="col-lg-12">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title">To Do List</h3>
        </div>

        <div class="help panel-body">
            <p>1. Double-Click to edit the tasks.</p>
            <p>2. Enter to save it.</p>
        </div>

        <ul class="list-group tasks"></ul>

        <div class="panel-footer">
            <button type="button" name="add" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New To Do
            </button>
        </div>
    </div>
</div>